name: Check legacy syntax
on:
  push:
    paths:
      - 'packages'
  pull_request:
    paths:
      - 'packages'
jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: cd scripts/admin/check-legacy-syntax && npm ci
      - name: Check syntax
        run: cd scripts/admin/check-legacy-syntax && node check-syntax.js 
