name: Meteor Docs
on:
  push:
    paths:
      - 'docs/**/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: guide/site/
    if:
      contains('
      refs/heads/devel
      refs/heads/master
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - name: Build the Guide
        run: npm ci && npm run build
      - name: Deploy to Netlify for preview
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './docs/public'
          production-branch: devel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          netlify-config-path: './docs/netlify.toml'
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GUIDE_SITE_ID }}
