name: Meteor Guide Devel
on:
  push:
    paths:
      - 'guide/**/*'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: guide/site/
    if:
      contains('
      refs/heads/devel
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Test build
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci && npm run build
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: guide/site/
    needs: [test]
    if:
      contains('
      refs/heads/devel
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build the Guide
        run: npm ci && npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './guide/site/public'
          production-branch: devel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Deploy from GitHub Actions devel
          netlify-config-path: './guide/netlify.toml'
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GUIDE_SITE_ID }}
