name: Meteor Guide PR
on:
  pull_request:
    paths:
      - 'guide/**/*'
jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: guide/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Build the Guide
        run: npm ci && npm run build
      - name: Deploy to Netlify for preview
        uses: nwtgck/actions-netlify@v2.1.0
        with:
          publish-dir: './guide/public'
          production-branch: devel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Deploy from GitHub Actions ${{ github.event.pull_request.title }}
          netlify-config-path: './guide/netlify.toml'
          alias: deploy-preview-${{ github.event.number }}
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GUIDE_SITE_ID }}
