name: Meteor Selftest Windows

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - devel
      - 2.x.x

env:
  METEOR_PRETTY_OUTPUT: 0
  SELF_TEST_TOOL_NODE_FLAGS: ' '
  TOOL_NODE_FLAGS: --expose-gc
  TIMEOUT_SCALE_FACTOR: 20
  METEOR_HEADLESS: true
  SELF_TEST_EXCLUDE: '^NULL-LEAVE-THIS-HERE-NULL$'

jobs:
  test:
    runs-on: windows-2019-meteor
    concurrency:
      group: ${{ github.head_ref }}-meteor-selftest-windows
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        shell: pwsh
        run: |
          $env:PATH = "C:\Program Files\7-Zip;$env:PATH"
          .\scripts\windows\ci\install.ps1

      - name: Run tests
        shell: pwsh
        run: |
          $env:PATH = "C:\Program Files\7-Zip;$env:PATH"
          .\scripts\windows\ci\test.ps1

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            .\dev_bundle
            .\.babel-cache
            .\.meteor
          key: ${{ runner.os }}-meteor-${{ hashFiles('**/package-lock.json') }}
